-- Mobile inventory operations and standards-based Web Push subscriptions.

ALTER TABLE public.inventory_items
  ADD COLUMN IF NOT EXISTS target_stock numeric(12,3) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS preferred_supplier text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS storage_location text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS count_frequency_days integer NOT NULL DEFAULT 7,
  ADD COLUMN IF NOT EXISTS tracks_expiry boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS last_counted_at timestamptz;

UPDATE public.inventory_items
SET target_stock = GREATEST(target_stock, minimum_stock, current_stock, 0)
WHERE target_stock < minimum_stock OR target_stock = 0;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'inventory_items_target_stock_check'
      AND conrelid = 'public.inventory_items'::regclass
  ) THEN
    ALTER TABLE public.inventory_items
      ADD CONSTRAINT inventory_items_target_stock_check
      CHECK (target_stock >= minimum_stock);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'inventory_items_count_frequency_check'
      AND conrelid = 'public.inventory_items'::regclass
  ) THEN
    ALTER TABLE public.inventory_items
      ADD CONSTRAINT inventory_items_count_frequency_check
      CHECK (count_frequency_days BETWEEN 1 AND 365);
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.inventory_counts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  scope text NOT NULL DEFAULT 'full'
    CHECK (scope = ANY (ARRAY['full', 'critical'])),
  status text NOT NULL DEFAULT 'draft'
    CHECK (status = ANY (ARRAY['draft', 'submitted', 'reconciled', 'cancelled'])),
  notes text NOT NULL DEFAULT '',
  requires_review boolean NOT NULL DEFAULT false,
  started_by uuid NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  completed_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  reviewed_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  started_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  reviewed_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.inventory_count_lines (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  count_id uuid NOT NULL REFERENCES public.inventory_counts(id) ON DELETE CASCADE,
  inventory_item_id uuid NOT NULL REFERENCES public.inventory_items(id) ON DELETE RESTRICT,
  expected_stock numeric(12,3) NOT NULL,
  counted_stock numeric(12,3) CHECK (counted_stock >= 0),
  variance numeric(12,3) GENERATED ALWAYS AS (counted_stock - expected_stock) STORED,
  reason_code text NOT NULL DEFAULT '',
  note text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (count_id, inventory_item_id)
);

CREATE TABLE IF NOT EXISTS public.inventory_purchase_orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  status text NOT NULL DEFAULT 'draft'
    CHECK (status = ANY (ARRAY['draft', 'ordered', 'partially_received', 'received', 'cancelled'])),
  supplier text NOT NULL DEFAULT '',
  notes text NOT NULL DEFAULT '',
  created_by uuid NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  ordered_at timestamptz,
  expected_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.inventory_purchase_order_lines (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  purchase_order_id uuid NOT NULL REFERENCES public.inventory_purchase_orders(id) ON DELETE CASCADE,
  inventory_item_id uuid NOT NULL REFERENCES public.inventory_items(id) ON DELETE RESTRICT,
  ordered_quantity numeric(12,3) NOT NULL CHECK (ordered_quantity > 0),
  received_quantity numeric(12,3) NOT NULL DEFAULT 0 CHECK (received_quantity >= 0),
  expected_unit_cost numeric(12,2) NOT NULL DEFAULT 0 CHECK (expected_unit_cost >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (purchase_order_id, inventory_item_id)
);

CREATE TABLE IF NOT EXISTS public.inventory_receipts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  purchase_order_id uuid REFERENCES public.inventory_purchase_orders(id) ON DELETE SET NULL,
  supplier text NOT NULL DEFAULT '',
  notes text NOT NULL DEFAULT '',
  received_by uuid NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  received_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.inventory_receipt_lines (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  receipt_id uuid NOT NULL REFERENCES public.inventory_receipts(id) ON DELETE CASCADE,
  purchase_order_line_id uuid REFERENCES public.inventory_purchase_order_lines(id) ON DELETE SET NULL,
  inventory_item_id uuid NOT NULL REFERENCES public.inventory_items(id) ON DELETE RESTRICT,
  received_quantity numeric(12,3) NOT NULL CHECK (received_quantity > 0),
  unit_cost numeric(12,2) NOT NULL DEFAULT 0 CHECK (unit_cost >= 0),
  expires_on date,
  storage_location text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.inventory_lots (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  inventory_item_id uuid NOT NULL REFERENCES public.inventory_items(id) ON DELETE RESTRICT,
  receipt_line_id uuid UNIQUE REFERENCES public.inventory_receipt_lines(id) ON DELETE SET NULL,
  lot_code text NOT NULL DEFAULT '',
  quantity_received numeric(12,3) NOT NULL CHECK (quantity_received > 0),
  quantity_remaining numeric(12,3) NOT NULL CHECK (quantity_remaining >= 0),
  unit_cost numeric(12,2) NOT NULL DEFAULT 0 CHECK (unit_cost >= 0),
  expires_on date,
  storage_location text NOT NULL DEFAULT '',
  received_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.inventory_lots (
  inventory_item_id,
  lot_code,
  quantity_received,
  quantity_remaining,
  unit_cost,
  storage_location,
  received_at
)
SELECT
  item.id,
  'INICIAL',
  item.current_stock,
  item.current_stock,
  item.cost_per_unit,
  item.storage_location,
  item.created_at
FROM public.inventory_items item
WHERE item.current_stock > 0
  AND NOT EXISTS (
    SELECT 1
    FROM public.inventory_lots lot
    WHERE lot.inventory_item_id = item.id
  );

ALTER TABLE public.inventory_movements
  ADD COLUMN IF NOT EXISTS previous_stock numeric(12,3),
  ADD COLUMN IF NOT EXISTS resulting_stock numeric(12,3),
  ADD COLUMN IF NOT EXISTS reason_code text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS count_id uuid REFERENCES public.inventory_counts(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS receipt_id uuid REFERENCES public.inventory_receipts(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS lot_id uuid REFERENCES public.inventory_lots(id) ON DELETE SET NULL;

ALTER TABLE public.inventory_movements
  DROP CONSTRAINT IF EXISTS inventory_movements_movement_type_check;

ALTER TABLE public.inventory_movements
  ADD CONSTRAINT inventory_movements_movement_type_check
  CHECK (movement_type = ANY (ARRAY[
    'purchase',
    'adjustment',
    'consumption',
    'return',
    'waste',
    'count_correction',
    'internal_use',
    'damage',
    'expired'
  ]));

CREATE TABLE IF NOT EXISTS public.push_subscriptions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  endpoint text NOT NULL UNIQUE,
  p256dh text NOT NULL,
  auth_key text NOT NULL,
  device_label text NOT NULL DEFAULT '',
  user_agent text NOT NULL DEFAULT '',
  is_active boolean NOT NULL DEFAULT true,
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS inventory_counts_status_started_idx
  ON public.inventory_counts(status, started_at DESC);
CREATE INDEX IF NOT EXISTS inventory_counts_started_by_idx
  ON public.inventory_counts(started_by);
CREATE INDEX IF NOT EXISTS inventory_count_lines_count_idx
  ON public.inventory_count_lines(count_id, inventory_item_id);
CREATE INDEX IF NOT EXISTS inventory_count_lines_item_idx
  ON public.inventory_count_lines(inventory_item_id);
CREATE INDEX IF NOT EXISTS inventory_purchase_orders_status_created_idx
  ON public.inventory_purchase_orders(status, created_at DESC);
CREATE INDEX IF NOT EXISTS inventory_purchase_orders_created_by_idx
  ON public.inventory_purchase_orders(created_by);
CREATE INDEX IF NOT EXISTS inventory_purchase_order_lines_order_idx
  ON public.inventory_purchase_order_lines(purchase_order_id, inventory_item_id);
CREATE INDEX IF NOT EXISTS inventory_purchase_order_lines_item_idx
  ON public.inventory_purchase_order_lines(inventory_item_id);
CREATE INDEX IF NOT EXISTS inventory_receipts_order_idx
  ON public.inventory_receipts(purchase_order_id);
CREATE INDEX IF NOT EXISTS inventory_receipts_received_by_idx
  ON public.inventory_receipts(received_by);
CREATE INDEX IF NOT EXISTS inventory_receipt_lines_receipt_idx
  ON public.inventory_receipt_lines(receipt_id, inventory_item_id);
CREATE INDEX IF NOT EXISTS inventory_receipt_lines_item_idx
  ON public.inventory_receipt_lines(inventory_item_id);
CREATE INDEX IF NOT EXISTS inventory_receipt_lines_order_line_idx
  ON public.inventory_receipt_lines(purchase_order_line_id);
CREATE INDEX IF NOT EXISTS inventory_lots_expiry_idx
  ON public.inventory_lots(expires_on, inventory_item_id)
  WHERE quantity_remaining > 0 AND expires_on IS NOT NULL;
CREATE INDEX IF NOT EXISTS inventory_lots_item_fifo_idx
  ON public.inventory_lots(inventory_item_id, expires_on, received_at)
  WHERE quantity_remaining > 0;
CREATE INDEX IF NOT EXISTS inventory_movements_count_idx
  ON public.inventory_movements(count_id);
CREATE INDEX IF NOT EXISTS inventory_movements_receipt_idx
  ON public.inventory_movements(receipt_id);
CREATE INDEX IF NOT EXISTS inventory_movements_lot_idx
  ON public.inventory_movements(lot_id);
CREATE INDEX IF NOT EXISTS push_subscriptions_user_active_idx
  ON public.push_subscriptions(user_id, is_active)
  WHERE is_active;

ALTER TABLE public.inventory_counts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_count_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_purchase_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_purchase_order_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_receipt_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_lots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;

ALTER POLICY "Inventory items updatable by admins" ON public.inventory_items
  USING (public.get_user_role() IN ('owner', 'admin', 'kitchen', 'supervisor'))
  WITH CHECK (public.get_user_role() IN ('owner', 'admin', 'kitchen', 'supervisor'));

ALTER POLICY "Inventory movements created by admins" ON public.inventory_movements
  WITH CHECK (
    public.get_user_role() IN ('owner', 'admin', 'kitchen', 'supervisor')
    AND created_by = (SELECT auth.uid())
  );

CREATE POLICY "Inventory counts viewable by operators" ON public.inventory_counts
  FOR SELECT TO authenticated
  USING (public.get_user_role() IN ('owner', 'admin', 'kitchen', 'supervisor'));
CREATE POLICY "Inventory counts created by operators" ON public.inventory_counts
  FOR INSERT TO authenticated
  WITH CHECK (
    public.get_user_role() IN ('owner', 'admin', 'kitchen', 'supervisor')
    AND started_by = (SELECT auth.uid())
  );
CREATE POLICY "Inventory counts updated by operators" ON public.inventory_counts
  FOR UPDATE TO authenticated
  USING (public.get_user_role() IN ('owner', 'admin', 'kitchen', 'supervisor'))
  WITH CHECK (public.get_user_role() IN ('owner', 'admin', 'kitchen', 'supervisor'));

CREATE POLICY "Inventory count lines viewable by operators" ON public.inventory_count_lines
  FOR SELECT TO authenticated
  USING (public.get_user_role() IN ('owner', 'admin', 'kitchen', 'supervisor'));
CREATE POLICY "Inventory count lines managed by operators" ON public.inventory_count_lines
  FOR ALL TO authenticated
  USING (public.get_user_role() IN ('owner', 'admin', 'kitchen', 'supervisor'))
  WITH CHECK (public.get_user_role() IN ('owner', 'admin', 'kitchen', 'supervisor'));

CREATE POLICY "Purchase orders viewable by operators" ON public.inventory_purchase_orders
  FOR SELECT TO authenticated
  USING (public.get_user_role() IN ('owner', 'admin', 'kitchen', 'supervisor'));
CREATE POLICY "Purchase orders created by operators" ON public.inventory_purchase_orders
  FOR INSERT TO authenticated
  WITH CHECK (
    public.get_user_role() IN ('owner', 'admin', 'kitchen', 'supervisor')
    AND created_by = (SELECT auth.uid())
  );
CREATE POLICY "Purchase orders updated by operators" ON public.inventory_purchase_orders
  FOR UPDATE TO authenticated
  USING (public.get_user_role() IN ('owner', 'admin', 'kitchen', 'supervisor'))
  WITH CHECK (public.get_user_role() IN ('owner', 'admin', 'kitchen', 'supervisor'));

CREATE POLICY "Purchase order lines viewable by operators" ON public.inventory_purchase_order_lines
  FOR SELECT TO authenticated
  USING (public.get_user_role() IN ('owner', 'admin', 'kitchen', 'supervisor'));
CREATE POLICY "Purchase order lines managed by operators" ON public.inventory_purchase_order_lines
  FOR ALL TO authenticated
  USING (public.get_user_role() IN ('owner', 'admin', 'kitchen', 'supervisor'))
  WITH CHECK (public.get_user_role() IN ('owner', 'admin', 'kitchen', 'supervisor'));

CREATE POLICY "Receipts viewable by operators" ON public.inventory_receipts
  FOR SELECT TO authenticated
  USING (public.get_user_role() IN ('owner', 'admin', 'kitchen', 'supervisor'));
CREATE POLICY "Receipts created by operators" ON public.inventory_receipts
  FOR INSERT TO authenticated
  WITH CHECK (
    public.get_user_role() IN ('owner', 'admin', 'kitchen', 'supervisor')
    AND received_by = (SELECT auth.uid())
  );

CREATE POLICY "Receipt lines viewable by operators" ON public.inventory_receipt_lines
  FOR SELECT TO authenticated
  USING (public.get_user_role() IN ('owner', 'admin', 'kitchen', 'supervisor'));
CREATE POLICY "Receipt lines created by operators" ON public.inventory_receipt_lines
  FOR INSERT TO authenticated
  WITH CHECK (public.get_user_role() IN ('owner', 'admin', 'kitchen', 'supervisor'));

CREATE POLICY "Inventory lots viewable by staff" ON public.inventory_lots
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "Inventory lots managed by operators" ON public.inventory_lots
  FOR ALL TO authenticated
  USING (public.get_user_role() IN ('owner', 'admin', 'kitchen', 'supervisor'))
  WITH CHECK (public.get_user_role() IN ('owner', 'admin', 'kitchen', 'supervisor'));

CREATE POLICY "Users read own push subscriptions" ON public.push_subscriptions
  FOR SELECT TO authenticated
  USING (user_id = (SELECT auth.uid()));
CREATE POLICY "Users create own push subscriptions" ON public.push_subscriptions
  FOR INSERT TO authenticated
  WITH CHECK (user_id = (SELECT auth.uid()));
CREATE POLICY "Users update own push subscriptions" ON public.push_subscriptions
  FOR UPDATE TO authenticated
  USING (user_id = (SELECT auth.uid()))
  WITH CHECK (user_id = (SELECT auth.uid()));
CREATE POLICY "Users delete own push subscriptions" ON public.push_subscriptions
  FOR DELETE TO authenticated
  USING (user_id = (SELECT auth.uid()));

GRANT SELECT, INSERT, UPDATE ON public.inventory_counts TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.inventory_count_lines TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.inventory_purchase_orders TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.inventory_purchase_order_lines TO authenticated;
GRANT SELECT, INSERT ON public.inventory_receipts TO authenticated;
GRANT SELECT, INSERT ON public.inventory_receipt_lines TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.inventory_lots TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.push_subscriptions TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.inventory_purchase_orders_number_seq TO authenticated;

CREATE OR REPLACE FUNCTION private.sync_inventory_lots_from_movement()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  remaining numeric(12,3);
  lot_row record;
  take_quantity numeric(12,3);
  generated_lot_id uuid;
BEGIN
  IF NEW.quantity_change < 0 THEN
    remaining := ABS(NEW.quantity_change);

    FOR lot_row IN
      SELECT id, quantity_remaining
      FROM public.inventory_lots
      WHERE inventory_item_id = NEW.inventory_item_id
        AND quantity_remaining > 0
      ORDER BY expires_on ASC NULLS LAST, received_at ASC, id ASC
      FOR UPDATE
    LOOP
      EXIT WHEN remaining <= 0;
      take_quantity := LEAST(remaining, lot_row.quantity_remaining);

      UPDATE public.inventory_lots
      SET quantity_remaining = quantity_remaining - take_quantity
      WHERE id = lot_row.id;

      remaining := remaining - take_quantity;
    END LOOP;
  ELSIF NEW.quantity_change > 0
    AND NEW.lot_id IS NULL
    AND NEW.movement_type IN ('purchase', 'adjustment', 'return', 'count_correction')
  THEN
    INSERT INTO public.inventory_lots (
      inventory_item_id,
      lot_code,
      quantity_received,
      quantity_remaining,
      unit_cost,
      received_at
    )
    SELECT
      NEW.inventory_item_id,
      UPPER(NEW.movement_type),
      NEW.quantity_change,
      NEW.quantity_change,
      item.cost_per_unit,
      COALESCE(NEW.created_at, now())
    FROM public.inventory_items item
    WHERE item.id = NEW.inventory_item_id
    RETURNING id INTO generated_lot_id;

    NEW.lot_id := generated_lot_id;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trigger_sync_inventory_lots_from_movement
  ON public.inventory_movements;
CREATE TRIGGER trigger_sync_inventory_lots_from_movement
  BEFORE INSERT ON public.inventory_movements
  FOR EACH ROW
  EXECUTE FUNCTION private.sync_inventory_lots_from_movement();

CREATE OR REPLACE FUNCTION public.record_inventory_movement(
  p_inventory_item_id uuid,
  p_quantity_change numeric,
  p_movement_type text,
  p_reason_code text DEFAULT '',
  p_note text DEFAULT ''
)
RETURNS public.inventory_movements
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  current_item public.inventory_items%ROWTYPE;
  movement public.inventory_movements%ROWTYPE;
  next_stock numeric(12,3);
BEGIN
  IF public.get_user_role() NOT IN ('owner', 'admin', 'kitchen', 'supervisor') THEN
    RAISE EXCEPTION 'No tienes permiso para modificar inventario';
  END IF;

  IF p_quantity_change = 0 THEN
    RAISE EXCEPTION 'La cantidad debe ser diferente de cero';
  END IF;

  IF p_movement_type NOT IN (
    'purchase', 'adjustment', 'waste', 'internal_use', 'damage', 'expired'
  ) THEN
    RAISE EXCEPTION 'Tipo de movimiento no permitido';
  END IF;

  SELECT * INTO current_item
  FROM public.inventory_items
  WHERE id = p_inventory_item_id AND is_active
  FOR UPDATE;

  IF current_item.id IS NULL THEN
    RAISE EXCEPTION 'Insumo no encontrado';
  END IF;

  next_stock := current_item.current_stock + p_quantity_change;
  IF next_stock < 0 THEN
    RAISE EXCEPTION 'La existencia no puede quedar en negativo';
  END IF;

  UPDATE public.inventory_items
  SET current_stock = next_stock,
      updated_at = now()
  WHERE id = current_item.id;

  INSERT INTO public.inventory_movements (
    inventory_item_id,
    movement_type,
    quantity_change,
    note,
    created_by,
    previous_stock,
    resulting_stock,
    reason_code
  ) VALUES (
    current_item.id,
    p_movement_type,
    p_quantity_change,
    COALESCE(p_note, ''),
    (SELECT auth.uid()),
    current_item.current_stock,
    next_stock,
    COALESCE(p_reason_code, '')
  )
  RETURNING * INTO movement;

  RETURN movement;
END;
$$;

CREATE OR REPLACE FUNCTION public.start_inventory_count(p_scope text DEFAULT 'full')
RETURNS uuid
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  count_id uuid;
BEGIN
  IF public.get_user_role() NOT IN ('owner', 'admin', 'kitchen', 'supervisor') THEN
    RAISE EXCEPTION 'No tienes permiso para contar inventario';
  END IF;

  IF p_scope NOT IN ('full', 'critical') THEN
    RAISE EXCEPTION 'Tipo de conteo inválido';
  END IF;

  INSERT INTO public.inventory_counts (scope, started_by)
  VALUES (p_scope, (SELECT auth.uid()))
  RETURNING id INTO count_id;

  INSERT INTO public.inventory_count_lines (
    count_id,
    inventory_item_id,
    expected_stock
  )
  SELECT count_id, item.id, item.current_stock
  FROM public.inventory_items item
  WHERE item.is_active
    AND (p_scope = 'full' OR item.current_stock <= item.minimum_stock)
  ORDER BY item.name;

  RETURN count_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.complete_inventory_count(
  p_count_id uuid,
  p_lines jsonb,
  p_notes text DEFAULT ''
)
RETURNS text
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  count_row public.inventory_counts%ROWTYPE;
  line_input record;
  line_row public.inventory_count_lines%ROWTYPE;
  item_row public.inventory_items%ROWTYPE;
  delta numeric(12,3);
  next_stock numeric(12,3);
  material_difference boolean := false;
  final_status text;
  caller_role text;
BEGIN
  caller_role := public.get_user_role();
  IF caller_role NOT IN ('owner', 'admin', 'kitchen', 'supervisor') THEN
    RAISE EXCEPTION 'No tienes permiso para completar conteos';
  END IF;

  SELECT * INTO count_row
  FROM public.inventory_counts
  WHERE id = p_count_id
  FOR UPDATE;

  IF count_row.id IS NULL OR count_row.status <> 'draft' THEN
    RAISE EXCEPTION 'El conteo ya no se puede modificar';
  END IF;

  IF jsonb_typeof(p_lines) <> 'array' OR jsonb_array_length(p_lines) = 0 THEN
    RAISE EXCEPTION 'El conteo no contiene insumos';
  END IF;

  FOR line_input IN
    SELECT *
    FROM jsonb_to_recordset(p_lines) AS entry(
      line_id uuid,
      counted_stock numeric,
      reason_code text,
      note text
    )
    ORDER BY line_id
  LOOP
    SELECT * INTO line_row
    FROM public.inventory_count_lines
    WHERE id = line_input.line_id AND count_id = p_count_id
    FOR UPDATE;

    IF line_row.id IS NULL OR line_input.counted_stock IS NULL OR line_input.counted_stock < 0 THEN
      RAISE EXCEPTION 'Hay una cantidad de conteo inválida';
    END IF;

    delta := line_input.counted_stock - line_row.expected_stock;
    IF delta <> 0 AND COALESCE(line_input.reason_code, '') = '' THEN
      RAISE EXCEPTION 'Selecciona un motivo para cada diferencia';
    END IF;

    SELECT * INTO item_row
    FROM public.inventory_items
    WHERE id = line_row.inventory_item_id
    FOR UPDATE;

    next_stock := item_row.current_stock + delta;
    IF next_stock < 0 THEN
      RAISE EXCEPTION 'El inventario cambió durante el conteo. Inicia uno nuevo';
    END IF;

    UPDATE public.inventory_count_lines
    SET counted_stock = line_input.counted_stock,
        reason_code = COALESCE(line_input.reason_code, ''),
        note = COALESCE(line_input.note, ''),
        updated_at = now()
    WHERE id = line_row.id;

    IF delta <> 0 THEN
      UPDATE public.inventory_items
      SET current_stock = next_stock,
          last_counted_at = now(),
          updated_at = now()
      WHERE id = item_row.id;

      INSERT INTO public.inventory_movements (
        inventory_item_id,
        movement_type,
        quantity_change,
        note,
        created_by,
        previous_stock,
        resulting_stock,
        reason_code,
        count_id
      ) VALUES (
        item_row.id,
        'count_correction',
        delta,
        COALESCE(line_input.note, 'Corrección por conteo físico'),
        (SELECT auth.uid()),
        item_row.current_stock,
        next_stock,
        line_input.reason_code,
        p_count_id
      );

      IF ABS(delta * item_row.cost_per_unit) >= 300
        OR (
          line_row.expected_stock > 0
          AND ABS(delta) / line_row.expected_stock >= 0.20
        )
      THEN
        material_difference := true;
      END IF;
    ELSE
      UPDATE public.inventory_items
      SET last_counted_at = now(), updated_at = now()
      WHERE id = item_row.id;
    END IF;
  END LOOP;

  final_status := CASE
    WHEN material_difference AND caller_role NOT IN ('owner', 'admin') THEN 'submitted'
    ELSE 'reconciled'
  END;

  UPDATE public.inventory_counts
  SET status = final_status,
      notes = COALESCE(p_notes, ''),
      requires_review = material_difference,
      completed_by = (SELECT auth.uid()),
      completed_at = now(),
      reviewed_by = CASE WHEN final_status = 'reconciled' THEN (SELECT auth.uid()) ELSE NULL END,
      reviewed_at = CASE WHEN final_status = 'reconciled' THEN now() ELSE NULL END,
      updated_at = now()
  WHERE id = p_count_id;

  RETURN final_status;
END;
$$;

CREATE OR REPLACE FUNCTION public.review_inventory_count(p_count_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Solo administración puede conciliar esta diferencia';
  END IF;

  UPDATE public.inventory_counts
  SET status = 'reconciled',
      reviewed_by = (SELECT auth.uid()),
      reviewed_at = now(),
      updated_at = now()
  WHERE id = p_count_id AND status = 'submitted';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Conteo pendiente no encontrado';
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.create_inventory_purchase_order(
  p_supplier text,
  p_lines jsonb,
  p_notes text DEFAULT '',
  p_expected_at timestamptz DEFAULT NULL
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  order_id uuid;
  line_input record;
BEGIN
  IF public.get_user_role() NOT IN ('owner', 'admin', 'kitchen', 'supervisor') THEN
    RAISE EXCEPTION 'No tienes permiso para crear compras';
  END IF;

  IF jsonb_typeof(p_lines) <> 'array' OR jsonb_array_length(p_lines) = 0 THEN
    RAISE EXCEPTION 'Agrega al menos un insumo';
  END IF;

  INSERT INTO public.inventory_purchase_orders (
    status,
    supplier,
    notes,
    created_by,
    ordered_at,
    expected_at
  ) VALUES (
    'ordered',
    COALESCE(p_supplier, ''),
    COALESCE(p_notes, ''),
    (SELECT auth.uid()),
    now(),
    p_expected_at
  )
  RETURNING id INTO order_id;

  FOR line_input IN
    SELECT *
    FROM jsonb_to_recordset(p_lines) AS entry(
      inventory_item_id uuid,
      ordered_quantity numeric,
      expected_unit_cost numeric
    )
  LOOP
    IF line_input.inventory_item_id IS NULL OR line_input.ordered_quantity <= 0 THEN
      RAISE EXCEPTION 'Cantidad de compra inválida';
    END IF;

    INSERT INTO public.inventory_purchase_order_lines (
      purchase_order_id,
      inventory_item_id,
      ordered_quantity,
      expected_unit_cost
    ) VALUES (
      order_id,
      line_input.inventory_item_id,
      line_input.ordered_quantity,
      GREATEST(COALESCE(line_input.expected_unit_cost, 0), 0)
    );
  END LOOP;

  RETURN order_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.receive_inventory(
  p_purchase_order_id uuid,
  p_supplier text,
  p_lines jsonb,
  p_notes text DEFAULT ''
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  receipt_id uuid;
  receipt_line_id uuid;
  lot_id uuid;
  line_input record;
  item_row public.inventory_items%ROWTYPE;
  next_stock numeric(12,3);
  next_cost numeric(12,2);
BEGIN
  IF public.get_user_role() NOT IN ('owner', 'admin', 'kitchen', 'supervisor') THEN
    RAISE EXCEPTION 'No tienes permiso para recibir inventario';
  END IF;

  IF jsonb_typeof(p_lines) <> 'array' OR jsonb_array_length(p_lines) = 0 THEN
    RAISE EXCEPTION 'Agrega al menos un insumo recibido';
  END IF;

  IF p_purchase_order_id IS NOT NULL AND NOT EXISTS (
    SELECT 1
    FROM public.inventory_purchase_orders
    WHERE id = p_purchase_order_id
      AND status IN ('ordered', 'partially_received')
  ) THEN
    RAISE EXCEPTION 'La compra ya no está disponible para recepción';
  END IF;

  INSERT INTO public.inventory_receipts (
    purchase_order_id,
    supplier,
    notes,
    received_by
  ) VALUES (
    p_purchase_order_id,
    COALESCE(p_supplier, ''),
    COALESCE(p_notes, ''),
    (SELECT auth.uid())
  )
  RETURNING id INTO receipt_id;

  FOR line_input IN
    SELECT *
    FROM jsonb_to_recordset(p_lines) AS entry(
      purchase_order_line_id uuid,
      inventory_item_id uuid,
      received_quantity numeric,
      unit_cost numeric,
      expires_on date,
      storage_location text
    )
    ORDER BY inventory_item_id
  LOOP
    IF line_input.inventory_item_id IS NULL OR line_input.received_quantity <= 0 THEN
      RAISE EXCEPTION 'Cantidad recibida inválida';
    END IF;

    SELECT * INTO item_row
    FROM public.inventory_items
    WHERE id = line_input.inventory_item_id AND is_active
    FOR UPDATE;

    IF item_row.id IS NULL THEN
      RAISE EXCEPTION 'Insumo recibido no encontrado';
    END IF;

    INSERT INTO public.inventory_receipt_lines (
      receipt_id,
      purchase_order_line_id,
      inventory_item_id,
      received_quantity,
      unit_cost,
      expires_on,
      storage_location
    ) VALUES (
      receipt_id,
      line_input.purchase_order_line_id,
      item_row.id,
      line_input.received_quantity,
      GREATEST(COALESCE(line_input.unit_cost, 0), 0),
      line_input.expires_on,
      COALESCE(NULLIF(line_input.storage_location, ''), item_row.storage_location)
    )
    RETURNING id INTO receipt_line_id;

    INSERT INTO public.inventory_lots (
      inventory_item_id,
      receipt_line_id,
      lot_code,
      quantity_received,
      quantity_remaining,
      unit_cost,
      expires_on,
      storage_location,
      received_at
    ) VALUES (
      item_row.id,
      receipt_line_id,
      'REC-' || LEFT(receipt_id::text, 8),
      line_input.received_quantity,
      line_input.received_quantity,
      GREATEST(COALESCE(line_input.unit_cost, 0), 0),
      line_input.expires_on,
      COALESCE(NULLIF(line_input.storage_location, ''), item_row.storage_location),
      now()
    )
    RETURNING id INTO lot_id;

    next_stock := item_row.current_stock + line_input.received_quantity;
    next_cost := CASE
      WHEN next_stock <= 0 THEN GREATEST(COALESCE(line_input.unit_cost, 0), 0)
      WHEN line_input.unit_cost IS NULL OR line_input.unit_cost = 0 THEN item_row.cost_per_unit
      ELSE ROUND(
        (
          (GREATEST(item_row.current_stock, 0) * item_row.cost_per_unit)
          + (line_input.received_quantity * line_input.unit_cost)
        ) / next_stock,
        2
      )
    END;

    UPDATE public.inventory_items
    SET current_stock = next_stock,
        cost_per_unit = next_cost,
        storage_location = COALESCE(NULLIF(line_input.storage_location, ''), storage_location),
        tracks_expiry = tracks_expiry OR line_input.expires_on IS NOT NULL,
        updated_at = now()
    WHERE id = item_row.id;

    INSERT INTO public.inventory_movements (
      inventory_item_id,
      movement_type,
      quantity_change,
      note,
      created_by,
      previous_stock,
      resulting_stock,
      reason_code,
      receipt_id,
      lot_id
    ) VALUES (
      item_row.id,
      'purchase',
      line_input.received_quantity,
      'Recepción de mercancía',
      (SELECT auth.uid()),
      item_row.current_stock,
      next_stock,
      'receipt',
      receipt_id,
      lot_id
    );

    IF line_input.purchase_order_line_id IS NOT NULL THEN
      UPDATE public.inventory_purchase_order_lines
      SET received_quantity = received_quantity + line_input.received_quantity,
          updated_at = now()
      WHERE id = line_input.purchase_order_line_id
        AND purchase_order_id = p_purchase_order_id;
    END IF;
  END LOOP;

  IF p_purchase_order_id IS NOT NULL THEN
    UPDATE public.inventory_purchase_orders purchase_order
    SET status = CASE
          WHEN NOT EXISTS (
            SELECT 1
            FROM public.inventory_purchase_order_lines line
            WHERE line.purchase_order_id = purchase_order.id
              AND line.received_quantity < line.ordered_quantity
          ) THEN 'received'
          ELSE 'partially_received'
        END,
        updated_at = now()
    WHERE purchase_order.id = p_purchase_order_id;
  END IF;

  RETURN receipt_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.register_push_subscription(
  p_endpoint text,
  p_p256dh text,
  p_auth_key text,
  p_device_label text DEFAULT '',
  p_user_agent text DEFAULT ''
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  caller_id uuid := (SELECT auth.uid());
BEGIN
  IF caller_id IS NULL OR NOT EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE id = caller_id AND is_active
  ) THEN
    RAISE EXCEPTION 'Sesión no válida';
  END IF;

  IF COALESCE(p_endpoint, '') = ''
    OR COALESCE(p_p256dh, '') = ''
    OR COALESCE(p_auth_key, '') = ''
  THEN
    RAISE EXCEPTION 'Suscripción incompleta';
  END IF;

  INSERT INTO public.push_subscriptions (
    user_id,
    endpoint,
    p256dh,
    auth_key,
    device_label,
    user_agent,
    is_active,
    last_seen_at,
    updated_at
  ) VALUES (
    caller_id,
    p_endpoint,
    p_p256dh,
    p_auth_key,
    COALESCE(p_device_label, ''),
    COALESCE(p_user_agent, ''),
    true,
    now(),
    now()
  )
  ON CONFLICT (endpoint)
  DO UPDATE SET
    user_id = EXCLUDED.user_id,
    p256dh = EXCLUDED.p256dh,
    auth_key = EXCLUDED.auth_key,
    device_label = EXCLUDED.device_label,
    user_agent = EXCLUDED.user_agent,
    is_active = true,
    last_seen_at = now(),
    updated_at = now();
END;
$$;

REVOKE ALL ON FUNCTION private.sync_inventory_lots_from_movement() FROM PUBLIC;

REVOKE ALL ON FUNCTION public.record_inventory_movement(uuid, numeric, text, text, text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.start_inventory_count(text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.complete_inventory_count(uuid, jsonb, text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.review_inventory_count(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.create_inventory_purchase_order(text, jsonb, text, timestamptz) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.receive_inventory(uuid, text, jsonb, text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.register_push_subscription(text, text, text, text, text) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.record_inventory_movement(uuid, numeric, text, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.start_inventory_count(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.complete_inventory_count(uuid, jsonb, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.review_inventory_count(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_inventory_purchase_order(text, jsonb, text, timestamptz) TO authenticated;
GRANT EXECUTE ON FUNCTION public.receive_inventory(uuid, text, jsonb, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.register_push_subscription(text, text, text, text, text) TO authenticated;
